#!/usr/bin/env python3
import sys, json

"""
   read_json_key SPEC  (data on stdin)

  SPEC:
     a.b.c   doc["a"]["b"]["c"]

     0.b.c   doc[0]["b"]["c"]
"""

def walk(obj, path):
    lead = path.pop(0)
    if lead[0] in "0123456789":
        lead = int(lead, 10)
    sys.stderr.write(repr(lead) + "\n")
    val = obj[lead]
    if path:
        return walk(val, path)
    else:
        return val


if __name__ == "__main__":
    key = sys.argv[1]
    obj = json.load(sys.stdin)

    val = walk(obj, key.split("."))

    def output(val):
        if isinstance(val, (dict, list)):
            print(json.dumps(val))
        else:
            print(val)

    if isinstance(val, list):
        for x in val:
            output(x)
    else:
        output(val)

